# Generated by Django 5.1.7 on 2025-04-01 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=255)),
                ('inventory_number', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Equipment',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Places',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_status', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Status',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_of_using', models.DateField()),
                ('application_number', models.CharField(blank=True, max_length=255)),
                ('end_date_of_using', models.DateField(blank=True, null=True)),
                ('name_of_receiver', models.CharField(max_length=255)),
                ('equipment', models.ForeignKey(db_column='Equipment_id', on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment')),
                ('destination', models.ForeignKey(db_column='Destination_id', on_delete=django.db.models.deletion.CASCADE, to='equipment.place')),
            ],
            options={
                'db_table': 'Log',
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='location',
            field=models.ForeignKey(db_column='Location_id', on_delete=django.db.models.deletion.CASCADE, to='equipment.place'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='status',
            field=models.ForeignKey(db_column='Status_id', on_delete=django.db.models.deletion.CASCADE, to='equipment.status'),
        ),
    ]
